import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

// The wasm bundle is generated by `pnpm run wasm` (wasm-pack) and is not checked
// in. Skip these tests when it is absent so a fresh checkout still passes; CI
// builds the wasm before running them.
const wasmPath = fileURLToPath(new URL("../pkg/lmd_wasm_bg.wasm", import.meta.url));
const hasWasm = existsSync(wasmPath);

test("wasm runtime: build + check + specVersion", { skip: hasWasm ? false : "pkg not built" }, async () => {
  const core = await import("../src/index.js");
  await core.init(await readFile(wasmPath));

  const src = "---\nlmd: 1\nid: d\nversion: 1\ntitle: T\n---\n\n## Auth <!--lmd:a auth-->\n\nSee <!--lmd:ref :auth-->it<!--/lmd-->.\n";
  const doc = await core.build(src);

  assert.deepEqual(Object.keys(doc.manifest!.nodes), ["auth"]);
  assert.equal(doc.manifest!.edges.length, 1);
  assert.equal((await core.check(src)).filter((d) => d.severity === "error").length, 0);
  assert.equal(await core.specVersion(), 1);
});
