/**
 * A densely cross-linked single document. Many refs per section (single- and
 * multi-target) so the right column stays busy and the cards move a lot while
 * scrolling. Links use the wrapped-ref form:
 * `<!--lmd:ref targets-->source text<!--/lmd-->`.
 */
export const DEMO = [
  "# How a compiler works <!--lmd:a overview-->",
  "",
  "A compiler turns source code into a program a machine can run. It works in",
  "stages: the **front end** — <!--lmd:ref :lexer-->lexing<!--/lmd-->,",
  "<!--lmd:ref :parser-->parsing<!--/lmd-->, and",
  "<!--lmd:ref :sema-->semantic analysis<!--/lmd--> — understands your language,",
  "while the **back end** — <!--lmd:ref :optimizer-->optimization<!--/lmd--> and",
  "<!--lmd:ref :codegen-->code generation<!--/lmd--> — targets a machine. Between",
  "them sits an <!--lmd:ref :ir-->intermediate representation<!--/lmd-->.",
  "",
  "In one line, <!--lmd:ref covers=:lexer,:parser,:ast,:sema,:ir,:optimizer,:codegen-->source",
  "becomes tokens, a tree, checks, an IR, and finally machine code<!--/lmd-->.",
  "",
  "## Lexing <!--lmd:a lexer-->",
  "",
  "The <!--lmd:ref :lexer-->lexer<!--/lmd--> reads raw characters and groups them",
  "into *tokens*: keywords, identifiers, numbers, punctuation. It discards",
  "whitespace and comments, so the <!--lmd:ref :parser-->parser<!--/lmd--> never",
  "sees them. A token stream is much easier to work with than",
  "<!--lmd:ref refines=:overview-->raw source<!--/lmd-->, and it is the first thing",
  "the <!--lmd:ref :ast-->tree builder<!--/lmd--> consumes.",
  "",
  "## Parsing <!--lmd:a parser-->",
  "",
  "The parser takes tokens from the <!--lmd:ref :lexer-->lexer<!--/lmd--> and builds",
  "an <!--lmd:ref :ast-->abstract syntax tree<!--/lmd--> from the",
  "<!--lmd:ref :overview-->language grammar<!--/lmd-->. A mismatch is a syntax",
  "error. Parsing and <!--lmd:ref related=:sema,:ast-->the checks that follow<!--/lmd-->",
  "are what turn a flat stream into structure.",
  "",
  "## The syntax tree <!--lmd:a ast-->",
  "",
  "The <!--lmd:ref :ast-->abstract syntax tree<!--/lmd--> is your program as data:",
  "an expression is a node with children. Every later stage walks it —",
  "<!--lmd:ref annotates=:sema-->semantic analysis<!--/lmd-->,",
  "<!--lmd:ref lowers_to=:ir-->lowering to the IR<!--/lmd-->, and everything the",
  "<!--lmd:ref :optimizer-->optimizer<!--/lmd--> touches downstream. It comes",
  "straight from the <!--lmd:ref :parser-->parser<!--/lmd-->.",
  "",
  "## Semantic analysis <!--lmd:a sema-->",
  "",
  "Semantic analysis checks what a grammar cannot: are names declared, do types",
  "line up. It decorates the <!--lmd:ref :ast-->AST<!--/lmd--> with types, and",
  "rejects programs that <!--lmd:ref :parser-->parse<!--/lmd--> yet make no sense.",
  "Only once it passes do we trust the tree enough to build the",
  "<!--lmd:ref :ir-->IR<!--/lmd--> and move to the",
  "<!--lmd:ref related=:optimizer,:codegen-->back end<!--/lmd-->.",
  "",
  "## Intermediate representation <!--lmd:a ir-->",
  "",
  "The <!--lmd:ref :ir-->IR<!--/lmd--> is a simpler, machine-independent form —",
  "see the <!--lmd:ref glossary:ir-term-->glossary definition<!--/lmd-->.",
  "Because both the <!--lmd:ref part_of=:overview-->front end<!--/lmd--> and the",
  "<!--lmd:ref :optimizer-->optimizer<!--/lmd--> agree on it, you can support many",
  "<!--lmd:ref :lexer,:parser-->source languages<!--/lmd--> and many",
  "<!--lmd:ref :codegen-->target machines<!--/lmd--> without writing every pair. The",
  "shared IR is the whole point of the",
  "<!--lmd:ref design:passes-->pass manager<!--/lmd--> design.",
  "",
  "## Optimization <!--lmd:a optimizer-->",
  "",
  "The optimizer rewrites the <!--lmd:ref :ir-->IR<!--/lmd--> to be faster or",
  "smaller — folding constants, deleting dead code, inlining calls — without",
  "changing what it computes. It sits between the",
  "<!--lmd:ref :sema-->checked tree<!--/lmd--> and",
  "<!--lmd:ref :codegen-->code generation<!--/lmd-->, and it is the one stage you",
  "can run <!--lmd:ref refines=:ir,:optimizer-->again and again<!--/lmd-->. Removing",
  "a pass is governed by the",
  "<!--lmd:ref policy:deprecation-->deprecation policy<!--/lmd-->.",
  "",
  "## Code generation <!--lmd:a codegen-->",
  "",
  "Code generation walks the optimized <!--lmd:ref :ir-->IR<!--/lmd-->, emits",
  "machine instructions, assigns registers, and lays out memory. It is the last",
  "step of the <!--lmd:ref covers=:overview,:lexer,:parser,:sema,:ir,:optimizer-->whole",
  "pipeline<!--/lmd-->, turning the work of the <!--lmd:ref :optimizer-->optimizer<!--/lmd-->",
  "into something the CPU can finally run.",
].join("\n");
