/** A small, densely interlinked demo document for the reader. */
export const DEMO = [
  "# Espresso <!--lmd:a espresso-->",
  "",
  "Espresso is a concentrated coffee made by forcing hot [water](:water) through a bed",
  "of finely [ground](:grind) coffee under pressure. Its whole character comes down to",
  "the [extraction](:extraction) — how much you pull from the grounds, and how evenly.",
  "",
  "## Grind <!--lmd:a grind-->",
  "",
  "Grind size is the single biggest lever. Too coarse and water races through; too fine",
  "and it chokes. It sets up the [extraction](:extraction) and must be matched to your",
  "[dose](:dose). A good [machine](:machine) cannot rescue a bad grind.",
  "",
  "## Dose <!--lmd:a dose-->",
  "",
  "Dose is how many grams go in the basket. Pair it with the [grind](:grind) and a target",
  "ratio to the [water](:water) you pour out — a classic shot is 1:2 in about 28 seconds.",
  "",
  "## Extraction <!--lmd:a extraction-->",
  "",
  "Extraction is what you dissolve out of the [grind](:grind). Under-extracted shots taste",
  "sour; over-extracted ones taste bitter. You steer it with [dose](:dose), grind, and",
  "[water](:water) temperature.",
  "",
  "## Water <!--lmd:a water-->",
  "",
  "Water is ninety percent of the cup. Temperature and minerals both shape the",
  "[extraction](:extraction); most people land near 93°C. Hard water can scale up the",
  "[machine](:machine).",
  "",
  "## Milk <!--lmd:a milk-->",
  "",
  "Steamed milk turns an [espresso](:espresso) into a cappuccino or latte. Good microfoam",
  "is about texture, and it should complement the shot, not bury the [extraction](:extraction).",
  "",
  "## Machine <!--lmd:a machine-->",
  "",
  "The machine's job is stable pressure and stable [water](:water) temperature. Nine bars",
  "is the tradition. Beyond that it just needs to stay out of the way of your [grind](:grind)",
  "and [dose](:dose).",
].join("\n");
