/**
 * A ~2000-character single document, richly cross-linked to specific anchors
 * inside itself. Selecting a link focuses the target anchor within this same
 * document.
 */
export const DEMO = [
  "# How a compiler works <!--lmd:a overview-->",
  "",
  "A compiler turns source code into a program a machine can run. It works in",
  "stages, each feeding the next. The **front end** understands your language;",
  "the **back end** targets a machine. Between them sits an",
  "[intermediate representation](:ir) that keeps the two halves independent, so",
  "you can reuse the [optimizer](:optimizer) and [code generator](:codegen)",
  "across many languages.",
  "",
  "In one sentence: source becomes tokens, then a tree, then checks, an IR, and",
  "finally machine code. <!--lmd:rel related=:lexer,:parser,:sema,:codegen-->",
  "",
  "## Lexing <!--lmd:a lexer-->",
  "",
  "The lexer — or scanner — reads raw characters and groups them into *tokens*:",
  "keywords, identifiers, numbers, punctuation. It discards whitespace and",
  "comments. Its output is a flat stream the [parser](:parser) can consume",
  "without ever worrying about individual characters again.",
  "",
  "## Parsing <!--lmd:a parser-->",
  "",
  "The parser takes the token stream from the [lexer](:lexer) and builds an",
  "[abstract syntax tree](:ast) by following the language grammar. When the",
  "tokens do not fit that grammar, this is exactly where a syntax error is",
  "raised and reported back to you.",
  "",
  "## The syntax tree <!--lmd:a ast-->",
  "",
  "The abstract syntax tree is your program as structured data: an expression",
  "becomes a node with child nodes. Every later stage walks this tree.",
  "[Semantic analysis](:sema) annotates it, and *lowering* turns it into the",
  "[intermediate representation](:ir).",
  "",
  "## Semantic analysis <!--lmd:a sema-->",
  "",
  "Semantic analysis checks what a grammar cannot: are names declared, do types",
  "line up, is a `break` really inside a loop. It decorates the [AST](:ast) with",
  "types and resolved symbols, and rejects programs that [parse](:parser)",
  "cleanly yet make no sense.",
  "",
  "## Intermediate representation <!--lmd:a ir-->",
  "",
  "The IR is a simpler, machine-independent form of the program. Because both",
  "the [front end](:overview) and the [optimizer](:optimizer) agree on this one",
  "shape, you can support many source languages and many target machines without",
  "writing every combination by hand.",
  "",
  "## Optimization <!--lmd:a optimizer-->",
  "",
  "The optimizer rewrites the [IR](:ir) to be faster or smaller without changing",
  "what the program computes — folding constants, deleting dead code, inlining",
  "calls. It runs right before the final stage, [code generation](:codegen).",
  "",
  "## Code generation <!--lmd:a codegen-->",
  "",
  "Code generation walks the optimized [IR](:ir), emits instructions for a real",
  "machine, assigns registers, and lays out memory. What comes out is something",
  "the CPU can finally run — the whole [pipeline](:overview) in one artifact.",
].join("\n");
